apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    DB_PASSWORD: AgBIK+WcHwGzdN+/8rxTO2NifO3oifeITE0F+qIracGhEQs0hCj4u9xoRWo6mQ/imOWGYU0vcVyGhOy+W5/0LtGQhoOkXXmQmUZDqn5sK6KvkK+j6fzi0a+DkZ+VYftTnnbQfDr80rvR3pUPpyRrqYUVH4Of2zup140Ps7UAcQLvj1bhppyXQ1k7MDgje73H6alYjp6cCOD1bBiGGoS3tf6OuxoAnOSW4sftS1y2GgwjFi7ctVKia6aJIB+2tjltgtLrNVKck4VR9T5NBH3/XEH0icNRHX7cHYdejO7u+RZbWEyjlsXTDfUYy9NzT0Bn6GNme7YiGpvprfRrwEKfp1xFy4XCJW1I74EgGdqw3RHyGMPV4vAAfvyCCEdWhDulPgy212RxFmZkPXjxMdW1pAEiSlcLTmoE0TGmQ12inrrftkd4aJX8dztnak6sQCID0dGTTrzJrkoS1lVhitBieBsFrA9oryzU2P2/lFTS3SGYjAv6Omty9yYcXtCxDX/raEeDWNcUjpWg/p27Ofyq0XPRlAKrURZErTokSprQvvn85H2o1cdJ5TFW9mtUYzMKrPAl0UT5qxVo05LDp0LrInnOLpTr7/Tf1bXDqH3SmJqFrFQ+Pr3461JpL3u5ZZwCPu1abVdrE5eWIs0nie1tsDJnkXzlG5YTcT7r5/CyM1PoMNARCguxB2LDw6jEorCaWqB1TEvtG8Uo9w==
    DB_USER: AgAdG5/YB4yE+9GHdeAVQSSl34hpAApfO/18y8mwKDPAOC1IaiQ+j3dF65+gcTvM0iBd9FDmFMCkVkeB59Kval3Z1AnGsHsvaMxHTTkHfj3CNcGlITpgjCwe4ulrNYih6GliLfM7cA5ULuy/JzwXXQtRLEhT6Kr4pp3ovppJAgD4bTp1pFTs7fNhfUgSkWvYQ4rAykENzZsxABQk7BiBlgrIczHz68zrB+XbYNMyUQU/vrRMlkoVkwvLNobpQQNxlxAbb1XE09E0NQjOsiOGGqHu/ObUwURVX7vUJlfAO4Ld4qfoQ3c9OBBHKipCc4VsHuyKAROm5I7nycue1QzKbwJZNNf4KHqlBQKgU4G8Hv/Rh/o4+wfrXIyWdAhMZ+E8qZGvAfYjoiEwDYaCnxfgyowITK7PhyAtpO7O8ZsU79UAB6ekXc4YFQmQiI2UsWhc6c8HkmHU40OHLaJFMN20c4QooSPacR98U1M0a64vkTJ4Tlc8u8uRTy0LMwghCla63gmGt3lrup6XIeDBg2ajniiVsWLBKLLmBM2clALT69Lfr4b3cuSG8lynYq+5LKXk4VSVJsYvLbUftiRB7WOEWzEMFYgWdIsDbGklURm4DozEzVp9aMx2X/MqWxAmj1g8dWgCMVw1nMhfnC0E0zda9cS6QhuIGZUY3kfl5FQD8N2+Tw6YnQmBF28val1ufyqfQhzpYdBTzkTn2g==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-prod
    type: Opaque

